blogproject/blog/urls.py
from django.conf.urls import url
from . import views

# 视图函数命名空间。告诉 Django 这个 urls.py 是属于 blog 应用的
app_name = 'blog'
urlpatterns = [
    # name 参数，作为处理函数 index 的别名
    # url(r'^$', views.index, name='index'),
    # 修改URL，调用类视图的as_view()方法，
    url(r'^$', views.IndexView.as_view(), name='index'),
    # (?P<pk>[0-9]+) 表示命名捕获组，作用是从用户访问的URL里把括号内匹配的字符串捕获并作为关键字参数传给对应的视图函数
    # url(r'^post/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.PostDetailView.as_view(), name='detail'),
    # url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[1-9]{1,2})/$', views.archives, name='archives'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$', views.ArchivesView.as_view(), name='archives'),
    # url(r'^category/(?P<pk>[0-9]+)/$', views.category, name='category'),
    url(r'^category/(?P<pk>[0-9]+)/$', views.CategoryView.as_view(), name='category'),
    url(r'tag/(?P<pk>[0-9]+)/$', views.TagView.as_view(), name='tag'),
    # url(r'^search/$', views.search, name='search'),
]

blogproject/blogproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    # include 会将前面的字符串与后面 blog.urls 中写的URL拼接
    url(r'blog/', include('blog.urls')),
    url(r'', include('comments.urls')),
    url(r'^search/', include('haystack.urls')),
]

blogproject/comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$', views.post_comment, name='post_comment'),
]

blogproject/blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
import markdown
from django.utils.html import strip_tags


# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Post(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    created_time = models.DateTimeField()
    # 最后一次修改时间
    modified_time = models.DateTimeField()
    # 摘要，blank=True 允许该字段为空
    excerpt = models.CharField(max_length=200, blank=True)
    # 一对多关系
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    # 多对多关系
    tag = models.ManyToManyField(Tag, blank=True)
    # django.contrib.auth 是 Django 内置应用，专门处理网站用户的注册、登录等流程，User 是 Django 已经写好的用户模型
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.title

    # 自定义方法
    # 首先找到 blog 应用下的 detail 视图函数，然后 reverse 函数会去解析 detail 对应的URL
    # 此时对应的 URl 规则是 post/(?P<pk>[0-9]+)/ 正则表达式，正则表达式后面部分会被传入的参数 pk 所替换
    # 例如 post.pk 是 24，URL 就为 post/24/
    def get_absolute_url(self):
        return reverse('blog:detail', kwargs={'pk': self.pk})

    # 阅读量自增
    def increase_views(self):
        self.views += 1
        # update_fields 规定只更新的字段，提高效率
        self.save(update_fields=['views'])

    # 自动生成摘要
    def save(self, *args, **kwargs):
        if not self.excerpt:
            # 实例化一个markdown对象，用于渲染body的文本
            md = markdown.Markdown(extensionns=[
                'markdown.extensions.extra',
                'markdown.extensions.codehilite',
            ])
            # 先将Marrkdown文本渲染成html文本，然后通过strip_tags方法去掉HTML标签，截取前54个字符
            self.excerpt = strip_tags(md.convert(self.body))[:54]
        # 调用父类save()方法
        super(Post, self).save(*args, **kwargs)

    # 通过定义内部类，指定获取的文章排列方式，可以去掉视图函数中获取文章列表时重复的排序代码
    class Meta:
        ordering = ['-created_time']

blogproject/comments/models.py
from django.db import models


# Create your models here.
class Comment(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=255)
    url = models.URLField(blank=True)
    text = models.TextField()
    created_time = models.DateTimeField(auto_now_add=True)

    # 如果要关联的对象在另外一个app中，可以显式的指出
    post = models.ForeignKey('blog.Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:20]

blogproject/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Category, Tag
from comments.forms import CommentForm
import markdown
from django.views.generic import ListView, DetailView
from django.utils.text import slugify
from markdown.extensions.toc import TocExtension
from django.db.models import Q
from django.core.paginator import Paginator
# from django.http import HttpResponse


# Create your views here.
# 主页面视图函数
def index(request):
    post_list = Post.objects.all()
    return render(request, 'blog/index.html', context={'post_list': post_list, })


# 主页面类视图
class IndexView(ListView):
    # 指定model为Post，即告诉Django要获取的模型是Post
    model = Post
    # 指定要渲染的模板
    template_name = 'blog/index.html'
    # 指定获取模型列表的数据保存的变量名，传递给模板
    context_object_name = 'post_list'
    # 规定一页显示3篇文章
    paginate_by = 3

    # 获取分页导航数据
    def pagination_data(self, paginator, page, is_paginated):
        if not is_paginated:
            # 如果没有分页，无需显示分页导航，不用任何导航条数据，返回空字典
            return {}
        # 当前左边连续页码
        left = []
        # 当前右边连续页码
        right = []
        # 当前页左边页码是否需要显示省略号
        left_has_more = False
        # 当前页右边页码是否需要显示省略号
        right_has_more = False
        # 是否需要显示第一页的页码，当左边连续页码包含第一页时，不需显示
        first = False
        # 是否需要显示最后一页的页码，当右边连续页码包含最后一页时，不需显示
        last = False
        # 当前请求页的页码
        page_num = page.number
        # 总页数
        total_page = paginator.num_pages
        # 获得页码列表，如4页就是[1,2,3,4]
        page_range = paginator.page_range

        if page_num == 1:
            # 第一页，则只需获取右侧页码，假如获取右边两页页码
            right = page_range[page_num:page_num + 2]
            if right[-1] < total_page - 1:
                # 如果右侧要显示页码比最后一页减一还要小，那么右侧需要显示省略号
                right_has_more = True
            if right[-1] < total_page:
                # 如果右侧要显示的最后一页页码比最后一页小，那么显示最后一页
                last = True
        elif page_num == total_page:
            # 最后一页，只需获取左边页码
            left = page_range[(page_num - 3) if (page_num - 3) > 0 else 0:page_num - 1]
            if left[0] > 2:
                # 如果左边页码列表第一页比2还大，那么显示省略号
                left_has_more = True
            if left[0] > 1:
                # 即左边页码列表第一页比1 大，那么显示第一页
                first = True
        else:
            # 用户请求的是中间的页码
            left = page_range[(page_num - 3) if (page_num - 3) > 0 else 0:page_num - 1]
            right = page_range[page_num:page_num + 2]
            if right[-1] < total_page - 1:
                right_has_more = True
            if right[-1] < total_page:
                last = True
            if left[0] > 2:
                left_has_more = True
            if left[0] > 1:
                first = True
        date = {
            'left': left,
            'right': right,
            'left_has_more': left_has_more,
            'right_has_more': right_has_more,
            'first': first,
            'last': last
        }
        return date

    # 覆写get_context_data方法
    def get_context_data(self, **kwargs):
        # 首先获得父类生成的传递给模板的字典
        context = super(IndexView, self).get_context_data(**kwargs)
        # 在父类生成的字典中已经存在分页相关的模板变量
        paginator = context.get('paginator')
        page = context.get('page_obj')
        is_paginated = context.get('is_paginated')
        pagination_data = self.pagination_data(paginator, page, is_paginated)
        # 将分页数据更新到context中
        context.update(pagination_data)
        # 返回context，让ListView使用这个模板变量中的字典去渲染模板
        return context


# 详情页面视图函数
def detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.increase_views()  # 阅读量+1
    post.body = markdown.markdown(post.body,
                                  extensions=
                                  ['markdown.extensions.extra',
                                   'markdown.extensions.codehilite',
                                   'markdown.extensions.toc',
                                   ])
    form = CommentForm()
    comment_list = post.comment_set.all()
    context = {'post': post,
               'form': form,
               'comment_list': comment_list}
    return render(request, 'blog/detail.html', context=context)


# 详情页类视图
class PostDetailView(DetailView):
    model = Post
    template_name = 'blog/detail.html'
    context_object_name = 'post'

    def get(self, request, *args, **kwargs):
        # 覆写get方法，每浏览一次文章，阅读数+1
        # get 方法返回的是一个HttpResponse实例
        # 当调用get方法之后，才会有 self.object 属性，为 Post 模型实例，也就是被访问的文章
        response = super(PostDetailView, self).get(request, *args, **kwargs)
        self.object.increase_views()
        return response

    def get_object(self, queryset=None):
        # 覆写此方法，对 post 的 body 进行渲染
        post = super(PostDetailView, self).get_object(queryset=None)
        md = markdown.Markdown(extensions=[
            'markdown.extensions.extra',
            'markdown.extensions.codehilite',
            # 'markdown.extensions.toc',
            # slugify --> 能够很好的处理中文，结合TocExtension处理markdown的锚点
            TocExtension(slugify=slugify),
        ])
        post.body = md.convert(post.body)
        # 利用markdown自动生成标题
        post.toc = md.toc
        return post

    def get_context_data(self, **kwargs):
        # post 已经通过DetailView传递给模板，然后把form表单和评论列表传递给模板
        # 在类视图中，这个需要传递的模板变量字典是通过 get_context_data 获得的
        # 而在视图函数中，是通过 render 函数传递的字典 context 传递给模板
        context = super(PostDetailView, self).get_context_data(**kwargs)
        comment_list = self.object.comment_set.all()
        form = CommentForm()
        context.update({
            'form': form,
            'comment_list': comment_list
        })
        return context
    # get_object 和 get_context_data 在 get 方法中调用


# 归档页面视图函数
def archives(request, year, month):
    post_list = Post.objects.filter(created_time__year=year,
                                    created_time__month=month)
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 归档类视图
class ArchivesView(IndexView):
    def get_queryset(self):
        year = self.kwargs.get('year')
        month = self.kwargs.get('month')
        return super(ArchivesView, self).get_queryset().filter(created_time__year=year,
                                                               created_time__month=month)


# 分类页面视图函数
def category(request, pk):
    cate = get_object_or_404(Category, pk=pk)
    post_list = Post.objects.filter(category=cate)
    return render(request, 'blog/index.html', context={'post_list': post_list})


# 分类类视图
class CategoryView(IndexView):
    def get_queryset(self):
        # 在类视图中，从 URL 捕获的命名组参数值保存在实例的 kwargs 属性
        # self.kwargs.get('pk') --> 获取从URL捕获的分类pk，然后调用父类的get_queryset()获取所有文章，在筛选该分类下的文章
        cate = get_object_or_404(Category, pk=self.kwargs.get('pk'))
        return super(CategoryView, self).get_queryset().filter(category=cate)


# 标签类视图
class TagView(IndexView):
    def get_queryset(self):
        tag = get_object_or_404(Tag, pk=self.kwargs.get('pk'))
        return super(TagView, self).get_queryset().filter(tag=tag)


def search(request):
    # 模板表单中name = q ,所以这里键也为 q
    q = request.GET.get('q')
    error_msg = ''

    if not q:
        error_msg = '请输入关键词'
        return render(request, 'blog/index.html', {'error_msg': error_msg})

    # icontains ,contains --> 包含，i --> 不区分大小写
    # Q 对象用于包装查询表达式，提供复杂的查询逻辑
    post_list = Post.objects.filter(Q(title__icontains=q) | Q(body__icontains=q))
    return render(request, 'blog/index.html', context={'error_msg': error_msg,
                                                       'post_list': post_list})

blogproject/templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">{{ post.title }}</h1>
        <div class="entry-meta">
            <span class="post-category"><a href="#">{{ post.category }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                      datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="#">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
    <div class="entry-content clearfix">
        {{ post.body|safe }}
        <div class="widget-tag-cloud">
            <ul>
                标签：
                {% for tag in post.tag.all %}
                <li><a href="{% url 'blog:tag' tag.pk %}"> {{ tag.name }}</a></li>
                {% endfor %}
            </ul>
        </div>
    </div>
</article>
<section class="comment-area" id="comment-area">
    <hr>
    <h3>发表评论</h3>
    <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
        {% csrf_token %}
        <div class="row">
            <div class="col-md-6">
                <label for="id_name">名字：</label>
                {{ form.name }}
                {{ form.name.errors }}
            </div>
            <div class="col-md-6">
                <label for="id_email">邮箱：</label>
                {{ form.email }}
                {{ form.email.errors }}
            </div>
            <div class="col-md-12">
                <label for="id_comment">评论：</label>
                {{ form.text }}
                {{ form.text.errors }}
                <button type="submit" class="comment-btn">发表</button>
            </div>
        </div>    <!-- row -->
    </form>
    <div class="comment-list-panel">
        <h3>评论列表，共 <span>{{ post.comment_set.count }}</span> 条评论</h3>
        <ul class="comment-list list-unstyled">
            {% for comment in comment_list %}
            <li class="comment-item">
                <span class="nickname">{{ comment.name }}</span>
                <time class="submit-date" datetime="2012-11-09T23:15:57+00:00">{{ comment.created_time }}</time>
                <div class="text">
                    {{ comment.text }}
                </div>
            </li>
            {% empty %}
            暂无评论！
            {% endfor %}
        </ul>
    </div>
</section>
{% endblock main %}
{% block toc %}
<div class="widget widget-content">
    <h3 class="widget-title">文章目录</h3>
    {{ post.toc|safe }}
</div>
{% endblock toc %}

blogproject/templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
{% if error_msg %}
    <p>{{ error_msg }}</p>
{% endif %}

{% for post in post_list %}
<article class="post post-{{ post.pk }}">
    <header class="entry-header">
        <h1 class="entry-title">
             <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </h1>
        <div class="entry-meta">
            <span class="post-category"><a href="{% url 'blog:category' post.category.pk %}">{{ post.category }}</a></span>
            <span class="post-date"><a href="#"><time class="entry-date"
                                                       datetime="2012-11-09T23:15:57+00:00">{{ post.created_time }}</time></a></span>
            <span class="post-author"><a href="#">{{ post.author }}</a></span>
            <span class="comments-link"><a href="{% url 'comments:post_comment' post.pk %}">{{ post.comment_set.count }} 评论</a></span>
            <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
        </div>
    </header>
        <div class="entry-content clearfix">
            <p>{{ post.excerpt }}</p>
            <div class="read-more cl-effect-14">
                <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
            </div>
        </div>
    </article>
{% empty %}
<div class="no-post">暂时还未发布文章！</div>
{% endfor %}

<!-- 简单分页 -->
{% if is_paginated %}
<div class="pagination-simple">
    <!--如果当前页还有上一页，显示上一页按钮 -->
    {% if page_obj.has_previous %}
        <a href="?page={{ page_obj.previous_page_number }}">上一页</a>
    {% endif %}
    <span class="current">第 {{ page_obj.number }} 页 / 共 {{ paginator.num_pages }} 页</span>
    <!-- 如果当前页还要下一页，显示下一页按钮 -->
    {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">下一页</a>
    {% endif %}
</div>
{% endif %}
<!-- 分页导航 -->
{% if is_paginated %}
<div class="pagination">
    <ul>
        {% if first %}
        <li><a href="?page=1">1</a></li>
        {% endif %}
        {% if left %}
            {% if left_has_more %}
            <span>...</span>
            {% endif %}
            {% for i in left %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
        {% endif %}
        <li><a href="?page={{ page_obj.number }}" style="color: red">{{ page_obj.number }}</a></li>
        {% if right %}
            {% for i in right %}
            <li><a href="?page={{ i }}">{{ i }}</a></li>
            {% endfor %}
            {% if right_has_more %}
            <span>...</span>
            {% endif %}
        {% endif %}
        {% if last %}
        <li><a href="?page={{ paginator.num_pages }}">{{ paginator.num_pages }}</a></li>
        {% endif %}
    </ul>
</div>
{% endif %}
{% endblock main %}